# Generated by Django 3.2.3 on 2021-06-01 13:11

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LambdaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(max_length=220)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(max_length=220)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=120)),
                ('manufacturer_partnumber', models.SlugField()),
                ('manufacturer_serienumber', models.SlugField()),
                ('manufacturer_date', models.DateField()),
                ('website', models.EmailField(max_length=254)),
                ('contractor', models.CharField(max_length=120)),
                ('contractor_partnumber', models.SlugField()),
                ('contractor_serienumber', models.SlugField()),
                ('part_number', models.SlugField()),
                ('principal_location', models.CharField(max_length=100)),
                ('record', models.TextField(blank=True, null=True)),
                ('record_date', models.DateField(auto_now_add=True)),
                ('cae_partname', models.CharField(max_length=120)),
                ('cae_partnumber', models.SlugField()),
                ('cae_serienumber', models.SlugField()),
                ('item_model', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('documentation', models.TextField(blank=True, null=True)),
                ('item_image', models.ImageField(upload_to=inventory.models.user_image_path)),
                ('item_type', models.CharField(choices=[('Original', 'original'), ('Simulated', 'simulated'), ('Modified', 'modified')], max_length=20)),
                ('item_characteristic', models.CharField(choices=[('Sim Part', 'Sim part'), ('Consumable', 'consumable'), ('Tool', 'tool'), ('PPE', 'ppe'), ('Office', 'office'), ('Building', 'building')], max_length=20)),
                ('IsConsumable', models.BooleanField(default=False)),
                ('spare_current', models.PositiveSmallIntegerField()),
                ('spare_required', models.PositiveSmallIntegerField()),
                ('spare_minimum', models.PositiveSmallIntegerField()),
                ('update_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Repaired', 'repaired'), ('New', 'new'), ('Refurbished', 'refurbished')], max_length=20)),
                ('obsolescence', models.BooleanField(default=False)),
                ('PN_replacement', models.SlugField(blank=True, null=True)),
                ('PN_compatible', models.SlugField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('restriction', models.CharField(choices=[('ITAR', 'itar'), ('Controlled', 'controlled')], max_length=20)),
                ('owner', models.CharField(choices=[('CAE', 'cae'), ('Customer', 'customer'), ('Other', 'other')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rspl', models.BooleanField(default=False)),
                ('life_deadline', models.DateField()),
                ('cal_recurrence', models.CharField(max_length=10)),
                ('rec_last_date', models.DateField()),
                ('rec_next_date', models.DateField()),
                ('warranty_end', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
