# Generated by Django 3.2.3 on 2021-06-02 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spare',
            name='IsConsumable',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='cae_partname',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='cae_partnumber',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='cae_serienumber',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='contractor_partnumber',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='contractor_serienumber',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='description',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='documentation',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='id',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='item_characteristic',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='item_image',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='item_model',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='manufacturer_date',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='manufacturer_partnumber',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='manufacturer_serienumber',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='principal_location',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='record',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='record_date',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='username',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='website',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=120)),
                ('manufacturer_partnumber', models.SlugField()),
                ('manufacturer_serienumber', models.SlugField()),
                ('manufacturer_date', models.DateField()),
                ('website', models.EmailField(max_length=254)),
                ('contractor', models.CharField(max_length=120)),
                ('contractor_partnumber', models.SlugField()),
                ('contractor_serienumber', models.SlugField()),
                ('part_number', models.SlugField()),
                ('principal_location', models.CharField(max_length=100)),
                ('record', models.TextField(blank=True, null=True)),
                ('record_date', models.DateField(auto_now_add=True)),
                ('cae_partname', models.CharField(max_length=120)),
                ('cae_partnumber', models.SlugField()),
                ('cae_serienumber', models.SlugField()),
                ('item_model', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('documentation', models.TextField(blank=True, null=True)),
                ('item_image', models.ImageField(upload_to=inventory.models.user_image_path)),
                ('item_type', models.CharField(choices=[('Original', 'original'), ('Simulated', 'simulated'), ('Modified', 'modified')], max_length=20)),
                ('item_characteristic', models.CharField(choices=[('Sim Part', 'Sim part'), ('Consumable', 'consumable'), ('Tool', 'tool'), ('PPE', 'ppe'), ('Office', 'office'), ('Building', 'building')], max_length=20)),
                ('IsConsumable', models.BooleanField(default=False)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='spare',
            name='item_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.item'),
            preserve_default=False,
        ),
    ]
