# Generated by Django 3.2.3 on 2021-06-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210602_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='IsConsumable',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cae_partnumber',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cae_serienumber',
        ),
        migrations.RemoveField(
            model_name='item',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='item',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='item',
            name='contractor_partnumber',
        ),
        migrations.RemoveField(
            model_name='item',
            name='contractor_serienumber',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='documentation',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_characteristic',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='manufacturer_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='manufacturer_partnumber',
        ),
        migrations.RemoveField(
            model_name='item',
            name='manufacturer_serienumber',
        ),
        migrations.RemoveField(
            model_name='item',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='principal_location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='record',
        ),
        migrations.RemoveField(
            model_name='item',
            name='record_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='username',
        ),
        migrations.RemoveField(
            model_name='item',
            name='website',
        ),
    ]
