# Generated by Django 3.2.3 on 2021-06-02 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_auto_20210602_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=120)),
                ('manufacturer_partnumber', models.SlugField()),
                ('manufacturer_serienumber', models.SlugField()),
                ('manufacturer_date', models.DateField()),
                ('website', models.EmailField(max_length=254)),
                ('contractor', models.CharField(max_length=120)),
                ('contractor_partnumber', models.SlugField()),
                ('contractor_serienumber', models.SlugField()),
                ('part_number', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='principal_location',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='record',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='record_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='username',
            field=models.OneToOneField(default=32, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
