# Generated by Django 3.2.3 on 2021-06-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_article_manufacturer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='website',
            field=models.URLField(max_length=254),
        ),
    ]
