# Generated by Django 3.2.3 on 2021-06-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_article_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='contractor_partnumber',
        ),
        migrations.RemoveField(
            model_name='article',
            name='contractor_serienumber',
        ),
        migrations.RemoveField(
            model_name='article',
            name='manufacturer_partnumber',
        ),
        migrations.RemoveField(
            model_name='article',
            name='manufacturer_serienumber',
        ),
        migrations.RemoveField(
            model_name='article',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='principal_location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='record',
        ),
        migrations.RemoveField(
            model_name='item',
            name='record_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='username',
        ),
    ]
