# Generated by Django 3.2.3 on 2021-06-02 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210602_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='record_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
